#! /bin/bash
	source /opt/intel/bin/ifortvars.sh intel64

	compiler=ifort 
#	flags=" -fpe0 -g -traceback -check"
	flags="-O3" 
	libs="-lmkl_intel_lp64 -lmkl_sequential -lmkl_core"

#	if [ "x$exe" == "x" ]; then
#		exe=step2
#	fi

	$compiler -c vector_class.f90 $flags

	$compiler -c bcg.f $flags 
	$compiler -c ilu0.f $flags 
	$compiler -c matvecCSR.f $flags
	$compiler -c io.f $flags 
	$compiler -c dsort.f $flags 


	$compiler -c tridiagonal_matrix_class.f90 $flags
	$compiler -c step2.f90 $flags
        $compiler -c step2_m.f90 $flags


	$compiler -o step2 step2.o tridiagonal_matrix_class.o vector_class.o bcg.o ilu0.o io.o dsort.o matvecCSR.o $flags $libs
	$compiler -o step2_m step2_m.o tridiagonal_matrix_class.o vector_class.o bcg.o ilu0.o io.o dsort.o matvecCSR.o $flags $libs

